name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Install
          run: npm ci
        - name: Build
          run: npm run build
        - name: Lint
          run: npm run lint
        - name: Deploy to Heroku
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
